version: '3.9'

services:
  # Wordpress
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: pedram
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: pedram
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      PMA_HOSTS: db
      MYSQL_PASSWORD: 123456
      MYSQL_USER: pedram

volumes:
  wordpress:
  db:
